name:  test_jupyter


#on:
#  push:
#    branches: 
#      #- dev

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    ### Every 3 hours
    - cron:  '0 */4 * * *'      

 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1


   
    - name: Set up Python 3.6.*
      uses: actions/setup-python@v1
      with:
        python-version: 3.6.*

      
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1

            
    #- uses: actions/cache@v1
    #  id: cache
    #  with:
    #    path: ~/.cache/pip
    #    key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    #    restore-keys: |
    #      ${{ runner.os }}-pip-
   
  
    - name: Cache pipenv virtualenv
      id: cache-pipenv
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Python/
        key: ${{ runner.os }}-venv-mlmodels-${{ hashFiles('**/requirements_fake.txt') }}



    - name: Install numpy
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: pip install numpy
 

    - name: Install repo requirements 1
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements.txt


    - name: Install repo requirements 2
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run:  |
        pip install -r requirements_fake.txt


    - name: Install repo
      run: pip install -e . -r requirements.txt   --no-deps


    - name: Install Jupyter
      run: pip install ipython


    - name: Repo path
      run: python  run_basic_check.py


    ########  Test running 
    - name: ml_test
      run: ml_test  --do test_jupyter
      
         




